const About = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-blue-50 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold text-gray-800 mb-4">About Pantry Pal</h1>
          <p className="text-xl text-gray-600">Your AI-Powered Cooking Companion</p>
        </div>

        {/* Main Content */}
        <div className="bg-white rounded-2xl shadow-xl p-8 md:p-12 mb-8">
          {/* Introduction */}
          <section className="mb-10">
            <div className="flex items-center justify-center mb-6 text-7xl">
              🍳
            </div>
            <h2 className="text-3xl font-bold text-gray-800 mb-4 text-center">What is Pantry Pal?</h2>
            <p className="text-lg text-gray-700 leading-relaxed">
              Pantry Pal is an innovative recipe generation platform powered by Google's Gemini AI. 
              Our mission is to help you create delicious meals with the ingredients you already have, 
              reducing food waste and inspiring culinary creativity.
            </p>
          </section>

          {/* Features */}
          <section className="mb-10">
            <h2 className="text-3xl font-bold text-gray-800 mb-6">✨ Features</h2>
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-gradient-to-br from-green-50 to-green-100 rounded-lg p-6">
                <div className="text-3xl mb-3">🤖</div>
                <h3 className="text-xl font-semibold text-gray-800 mb-2">AI-Powered Generation</h3>
                <p className="text-gray-700">
                  Get personalized recipes generated by Google Gemini AI based on your available ingredients and dietary preferences.
                </p>
              </div>

              <div className="bg-gradient-to-br from-blue-50 to-blue-100 rounded-lg p-6">
                <div className="text-3xl mb-3">💬</div>
                <h3 className="text-xl font-semibold text-gray-800 mb-2">Interactive Chat</h3>
                <p className="text-gray-700">
                  Ask questions about recipes and request modifications through our intelligent chat interface.
                </p>
              </div>

              <div className="bg-gradient-to-br from-purple-50 to-purple-100 rounded-lg p-6">
                <div className="text-3xl mb-3">🔐</div>
                <h3 className="text-xl font-semibold text-gray-800 mb-2">Secure Authentication</h3>
                <p className="text-gray-700">
                  Your recipes and preferences are safely stored with JWT-based authentication.
                </p>
              </div>

              <div className="bg-gradient-to-br from-yellow-50 to-yellow-100 rounded-lg p-6">
                <div className="text-3xl mb-3">🔍</div>
                <h3 className="text-xl font-semibold text-gray-800 mb-2">Smart Filtering</h3>
                <p className="text-gray-700">
                  Filter your saved recipes by diet type, difficulty level, and ingredients to find exactly what you need.
                </p>
              </div>

              <div className="bg-gradient-to-br from-pink-50 to-pink-100 rounded-lg p-6">
                <div className="text-3xl mb-3">🥗</div>
                <h3 className="text-xl font-semibold text-gray-800 mb-2">Diet Preferences</h3>
                <p className="text-gray-700">
                  Support for various dietary preferences including Vegetarian, Vegan, Keto, and Protein-focused diets.
                </p>
              </div>

              <div className="bg-gradient-to-br from-orange-50 to-orange-100 rounded-lg p-6">
                <div className="text-3xl mb-3">📱</div>
                <h3 className="text-xl font-semibold text-gray-800 mb-2">Responsive Design</h3>
                <p className="text-gray-700">
                  Access your recipes anywhere with our mobile-friendly, responsive interface.
                </p>
              </div>
            </div>
          </section>

          {/* How It Works */}
          <section className="mb-10">
            <h2 className="text-3xl font-bold text-gray-800 mb-6">🔧 How It Works</h2>
            <div className="space-y-4">
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-10 h-10 bg-green-600 text-white rounded-full flex items-center justify-center font-bold">
                  1
                </div>
                <div>
                  <h4 className="font-semibold text-gray-800 mb-1">Enter Your Ingredients</h4>
                  <p className="text-gray-700">Tell us what ingredients you have in your pantry.</p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-10 h-10 bg-green-600 text-white rounded-full flex items-center justify-center font-bold">
                  2
                </div>
                <div>
                  <h4 className="font-semibold text-gray-800 mb-1">Choose Your Diet</h4>
                  <p className="text-gray-700">Select your dietary preference or choose "Any" for all options.</p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-10 h-10 bg-green-600 text-white rounded-full flex items-center justify-center font-bold">
                  3
                </div>
                <div>
                  <h4 className="font-semibold text-gray-800 mb-1">Get AI-Generated Recipes</h4>
                  <p className="text-gray-700">Our Gemini AI generates multiple recipe options tailored to your inputs.</p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-10 h-10 bg-green-600 text-white rounded-full flex items-center justify-center font-bold">
                  4
                </div>
                <div>
                  <h4 className="font-semibold text-gray-800 mb-1">Chat & Customize</h4>
                  <p className="text-gray-700">Ask questions or request modifications through the interactive chat.</p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-10 h-10 bg-green-600 text-white rounded-full flex items-center justify-center font-bold">
                  5
                </div>
                <div>
                  <h4 className="font-semibold text-gray-800 mb-1">Save & Access Anytime</h4>
                  <p className="text-gray-700">All your recipes are automatically saved and accessible from your recipe library.</p>
                </div>
              </div>
            </div>
          </section>

          {/* Technology Stack */}
          <section className="mb-10">
            <h2 className="text-3xl font-bold text-gray-800 mb-6">⚙️ Technology Stack</h2>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="bg-gray-50 rounded-lg p-4">
                <h4 className="font-semibold text-gray-800 mb-2">Frontend</h4>
                <ul className="text-gray-700 space-y-1">
                  <li>• React 18</li>
                  <li>• Tailwind CSS</li>
                  <li>• Vite</li>
                  <li>• Axios</li>
                </ul>
              </div>

              <div className="bg-gray-50 rounded-lg p-4">
                <h4 className="font-semibold text-gray-800 mb-2">Backend</h4>
                <ul className="text-gray-700 space-y-1">
                  <li>• Node.js & Express</li>
                  <li>• MongoDB</li>
                  <li>• JWT Authentication</li>
                  <li>• Google Gemini AI</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Contact/Footer */}
          <section className="text-center pt-8 border-t border-gray-200">
            <p className="text-gray-600 mb-4">
              Have questions or suggestions? We'd love to hear from you!
            </p>
            <div className="flex justify-center gap-6 text-2xl">
              <span className="cursor-pointer hover:scale-110 transition-transform">📧</span>
              <span className="cursor-pointer hover:scale-110 transition-transform">💬</span>
              <span className="cursor-pointer hover:scale-110 transition-transform">🐦</span>
            </div>
          </section>
        </div>

        {/* Version Info */}
        <div className="text-center text-gray-500 text-sm">
          <p>Pantry Pal v1.0.0 • Built with ❤️ and AI</p>
        </div>
      </div>
    </div>
  );
};

export default About;
